databases:
  - name: foodhub-db
    databaseName: foodhub
    user: foodhub

services:
  - type: web
    name: foodhub
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pizza.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodhub-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4